### ISSUE TITLE
type inference issues due to exposed S types

### ISSUE THREAD

**Issue by ceedubs** [atnos-org/origami#53]
I've noticed that some of the methods have a return type like `Fold[M, A, B]`, but others expose the `S` type and return an `Aux`-like type of `Fold[M, A, B] { type S = S0 }` for some `S0` type. Is there a reason that this `S` type is sometimes exposed? In a number of cases it looks like it could be an accidental artifact of not adding an explicit return type.

Below is an example of when the `S` type can trip things up.

This compiles just fine:

```scala
(
  mean[Double],
  plus[Double]
).tupled
```

If you try to `map` over one of the outputs it no longer compiles, because `map` exposes the internal `S`, so Scala can't find a common `Functor` for the two items.

```scala
(
  mean[Double].map(_ * 100),
  plus[Double]
).tupled
```

If you use the `fmap` alias provided by Cats which doesn't expose the `S` type, it compiles:

```scala
(
  mean[Double].fmap(_ * 100),
  plus[Double]
).tupled
```

**Comment by trobert** [comment]
I also had some trouble caused by the inconsistency in the exposure of `S`.
It can easily bring scalac to infer existentials types. As instance, this simple code will require existentials to be enabled to compile:
```scala
val fold = folds.countUnique[String].zip(folds.count[String])
```

Existentials, in turn, can trigger weird compiler [bugs](scala/bug#12108).

I don't know whether `S` should be always hidden or exposed, but I agree at least it should be consistent.
I have written some code which relies on the knowledge of `S`, but you can argue this is a leaky implementation detail.
On the other hand, you can hide it yourself if necessary.

**Comment by etorreborre** [comment]
I think I had to expose `S` to enable some "chaining" to work. Is your proposal to hide `S` everywhere and maybe add additional functions, say `mapS` to expose it when necessary? I can give it a go.

@ceedubs sorry for the late answer, I was moving countries + vacations so a bit overwhelmed.

**Comment by etorreborre** [comment]
I removed the superfluous existentials in `6.1.0`. Please tell me if that works ok for you both.

**Comment by ceedubs** [comment]
@etorreborre this is great. Thank you!

**Comment by trobert** [comment]
I no longer need existentials in my codebase, that's great.
However I need to rework the code which was (ab)using S. But that's ok, I guess it's better like that.
(I think doubling every combinator, creator, with a S version would be kind of heavy).
